### ISSUE TITLE
zoo脚本对满级的处理出错

### ISSUE THREAD

**Issue by hdstar2009** [star261/jd#6]
小问题，修不修都可以，不过满级的话，也还做任务，目测没金币了。

{"code":0,"data":{"bizCode":-2,"bizMsg":"您已满级，不能再收集金币了哦~","success":false},"msg":"调用成功"}
(node:26204) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'inviteId' of undefined
    at dealReturn (/scripts/jd_zoo.js:592:45)
    at /scripts/jd_zoo.js:542:9
    at got.post.then.message (/scripts/jd_zoo.js:973:5772)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lsh26** [comment]
已增加
