### ISSUE TITLE
请问京喜工厂能开团为什么不参团

### ISSUE THREAD

**Issue by BSDxxxx** [star261/jd#7]
开始执行... 2021/6/23 下午9:21:57

更新任务状态成功

🔔京喜工厂开团, 开始!

====================共11个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/6/23 下午9:21:57=====================

获取到的团活动ID：bozIUUFcUdWpw3QdvPw==

******开始【京东账号1】jd_xz *********

团活动ID  bozIUUFcANuUdWpw31dvPw==
团ID  3K5Zk171FvpYAQzi1hhugg==

今日剩余开团次数：1次

开团情况:1/7

此团未达领取团奖励人数：7人

===============开始账号内参团===================
获取到的内部团ID3K5Zk171FvpYAQzi1hhugg==

🔔京喜工厂开团, 结束! 🕛 1.238 秒

更新任务状态成功

执行结束...

**Comment by lsh26** [comment]
原逻辑，脚本会记录当天哪些账号已经助力过参团，你多次执行时，就不会重复去助力参团

由于很多人提这个问题，现逻辑已修改为，不管账号是否在当天助力过人，每执行一遍脚本，便会尝试参团

**Comment by lsh26** [comment]
> 开始执行... 2021/6/23 下午9:21:57
> 
> 更新任务状态成功
> 
> 🔔京喜工厂开团, 开始!
> 
> ====================共11个京东账号Cookie=========
> 
> ==================脚本执行- 北京时间(UTC+8)：2021/6/23 下午9:21:57=====================
> 
> 获取到的团活动ID：bozIUUFcUdWpw3QdvPw==
> 
> ******开始【京东账号1】jd_xz *********
> 
> 团活动ID bozIUUFcANuUdWpw31dvPw==
> 团ID 3K5Zk171FvpYAQzi1hhugg==
> 
> 今日剩余开团次数：1次
> 
> 开团情况:1/7
> 
> 此团未达领取团奖励人数：7人
> 
> ===============开始账号内参团===================
> 获取到的内部团ID3K5Zk171FvpYAQzi1hhugg==
> 
> 🔔京喜工厂开团, 结束! 🕛 1.238 秒
> 
> 更新任务状态成功
> 
> 执行结束...
原逻辑，脚本会记录当天哪些账号已经助力过参团，你多次执行时，就不会重复去助力参团

由于很多人提这个问题，现逻辑已修改为，不管账号是否在当天助力过人，每执行一遍脚本，便会尝试参团
